//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile20160830
    {
        public string UserDisplayName { get; set; }
        public string DeviceOS { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> WhenChanged { get; set; }
        public int id { get; set; }
    }
}
